from setuptools import setup, find_packages

setup(
    name="source-tripletex-put",
    description="Airbyte connector generated by scaffold script",
    author="Tobbe",
    author_email="tobbe@example.com",
    packages=find_packages(),
    install_requires=[
        "airbyte-cdk",
        "requests",
    ],
    package_data={
        "source_tripletex_put": ["spec.json"],
    },
    include_package_data=True,

    extras_require={"dev": ["pytest"]},
    entry_points={
        "console_scripts": [
            "source-tripletex-put=source_tripletex_put.source:main",
        ],
    },
)
