name: Build Connector

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: source-tripletex-put

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests
        run: pytest -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: get-sha
        name: Get short commit SHA
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${{ github.repository_owner }}/source-tripletex-put:${{ steps.get-sha.outputs.short_sha }} \
            -t ghcr.io/${{  github.repository_owner }}/source-tripletex-put:latest \
            --push .
